### ISSUE TITLE
Make Columns sortable and include from column

### ISSUE THREAD

**Issue by ryanvgates** [albinsunnanbo/PickupMailViewer#7]
Can you make the columns(SentDate, To and Subject) sortable? Can you add a From column which shows the email address the message was sent from?

**Comment by albinsunnanbo** [comment]
Sorting would be fairly easy using https://datatables.net/
I've tried a From-column but I thought it took to much space, but I can try again and re evaluate my position.

If you have the time you are more than welcome to create a pull request with sorting using datatables.

    var options = {
            fixedHeader: true,
            paging: false,
            info: false,
            searching: false
        };

could be a reasonable starting point for datatables configuration.

**Comment by albinsunnanbo** [comment]
Created a separate issue for the "From" column in #9
